variables:
- group: TestBaseSecret

trigger:
 branches: 
  include:
    - main

stages:
  - stage: Build
    displayName: 'Build'
    jobs:
      - job:
        displayName: Create TestBase Package
        pool:
          vmImage: 'windows-latest'
        workspace:
          clean: true
        timeoutInMinutes: 0
        steps:
          - checkout: self

          - task: PowerShell@2
            displayName: "Build App"
            inputs:
              targetType: "inline"
              workingDirectory: 'Sample-App-src/Calculator'
              script: |
                $env:Path += ";$($env:WIX)Bin"
                $(build.SourcesDirectory)/Sample-App-src/Calculator/build.ps1

          - task: CopyFiles@2
            displayName: "Copy scripts"
            inputs:
              SourceFolder: "Samples/Package/Out-of-Box/Calculator-OOB-Sample"
              TargetFolder: "$(build.BinariesDirectory)"
              OverWrite: true

          - task: CopyFiles@2
            displayName: "Copy MSI"
            inputs:
              SourceFolder: "$(build.SourcesDirectory)/Sample-App-src/Calculator/windows_installer"
              Contents: '*.msi'
              TargetFolder: "$(build.BinariesDirectory)/Bin"
              OverWrite: true
          - task: ArchiveFiles@2
            displayName: "Archive zip"
            inputs:
              rootFolderOrFile: "$(build.BinariesDirectory)"
              includeRootFolder: false
              archiveFile: "$(Build.ArtifactStagingDirectory)/Calculator-$(build.BuildNumber).zip"
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Build Artifacts'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/Calculator-$(build.BuildNumber).zip'
              ArtifactName: 'drop'
              publishLocation: 'Container'

  - stage: 'Deploy'
    dependsOn: Build
    jobs:
      - job:
        displayName: 'DownloadPipelineArtifact job'
        pool:
          vmImage: 'windows-latest'
        steps:
        - task: DownloadPipelineArtifact@2
          inputs:
            buildType: 'current'
            artifactName: 'drop'
            targetPath: '$(Build.ArtifactStagingDirectory)/pipeline'
      - job: 
        displayName: 'DownloadBuildArtifacts job'
        pool:
          vmImage: 'windows-latest'
        steps:
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(Build.ArtifactStagingDirectory)/build'
              cleanDestinationFolder: true
